{
"selectwelldropdown":"//div[@class='system-rail-container']//span[contains(@class,'k-dropdown-wrap ')]",
"WellConfigPage":
{
"configurationTab":"//div[text()='Configuration']",
"wellconfigurationTab":"//div[text()='Well Configuration']",
"general":"//div[text()=' General ']",
"wellnameinput":"wellName",
"welltypedropdwn":"wellType",
"welltypename":"//li[text()='RRL']",
"welltypefetchtextfield":"//kendo-dropdownlist[@id='wellType']//span[@class='k-input']",
"scadatypedrpdwn":"scadaType",
"scadatypename":"//li[text()='CygNet']",
"scadatypefetchtextfield":"//kendo-dropdownlist[@id='scadaType']//span[@class='k-input']",
"cygnetdomaindrpdwn":"cygNetDomain",
"cygnetdomainname":"//li[text()='27212']",
"cygnetdomainfetchtextfield":"//kendo-dropdownlist[@id='cygNetDomain']//span[@class='k-input']",
"createnewwellbutton":"//button[@name='createNewWellButton']",
"cygnetservicedrpdwn":"//span[text()='Select service...']",
"cygnetservicename":"//li[text()='CYG_DEMO.UIS']",
"cygnetservicefetchtextfield":"//kendo-dropdownlist[@id='siteService']//span[@class='k-input']",
"facilitybutton":"//input[@id='facilityId']/following-sibling::button",
"facilityfetchtextfield":"facilityId",
"applybutton":"//button[text()=' Apply ']",
"commissioninput":"//kendo-datepicker//input",
"wellboreinput":"//kendo-combobox[@id='assembly']//input",
"wellborefetchtextfield":"assemblyAPI",
"boreholeinput":"//kendo-combobox[@id='subassembly']//input",
"boreholefetchtextfield":"subAssemblyAPI",
"intervalinput":"//input[@id='intervalAPI']",
"welldepthreference":"wellDepthDatum",
"welldepthreferencefetchtextfield":"//kendo-dropdownlist[@id='wellDepthDatum']//span[@class='k-input']",
"depthelevation":"//kendo-numerictextbox[@id='datumElevation']//input",
"groundelevation":"//kendo-numerictextbox[@id='datumGroundElevation']//input",
"wellstatusdrpdwn":"wellStatus",
"wellstatusfetchtextfield":"//kendo-dropdownlist[@id='wellStatus']//span[@class='k-input']",
"wellattributetab":"//div[text()=' Well Attributes ']",
"leasename":"//kendo-combobox[@name='lease']//input",
"fieldname":"//kendo-combobox[@name='field']//input",
"engineername":"//kendo-combobox[@name='engineer']//input",
"regionname":"//kendo-combobox[@name='geographicRegion']//input",
"foremanname":"//kendo-combobox[@name='foreman']//input",
"gaugername":"//kendo-combobox[@name='gaugerBeat']//input",
"savebutton":"//span[text()='Save']"
},
"NetworkConfigPage":
{
"networkconfigurationtab":"//div[text()='Network Configuration']"
}
}